#### Import Libraries

In [58]:
import pandas as pd

#### Import Data

In [59]:
# Import cleaned data that we created from Data preprocessing notebook
options_data_clean = pd.read_csv(r"C:\Users\Hassa\OneDrive - Loughborough University\current\Algorthmic Trading for Beginners\Data Management\datamodules\minute_options_data\options_data_raw_cleaned.csv",
                                index_col=None)

# Set the correct datetime index
options_data_clean.index = pd.to_datetime(options_data_clean["expire_date"])
options_data_clean.index.name = ""

options_data_clean = options_data_clean.drop(columns=["Unnamed: 0"])

In [60]:
options_data_clean.head()

,symbol,underlying_last,expire_date,expiry_type,dte,strike,strike_distance,strike_distance_pct,c_delta,c_gamma,...,p_gamma,p_vega,p_theta,p_rho,p_iv,p_volume,p_last,p_size,p_bid,p_ask
,,,,,,,,,,,,,,,,,,,,,
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4250.0,-58.27,-0.014,0.58545,0.00036,...,0.00036,33.76342,-4.23265,-0.0,0.58064,205.0,2077.43,3 x 7,1915.47,2253.08
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4255.0,-53.27,-0.012,0.57824,0.00040,...,0.00040,33.76342,-3.81277,-0.0,0.51929,169.0,2081.41,3 x 6,1920.42,2255.89
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4260.0,-48.27,-0.011,0.57101,0.00045,...,0.00045,33.76342,-3.43054,-0.0,0.46344,216.0,2085.45,1 x 17,1925.43,2258.77
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4265.0,-43.27,-0.010,0.56374,0.00051,...,0.00051,33.76342,-3.08596,-0.0,0.41309,199.0,2089.57,10 x 7,1930.53,2261.71
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4270.0,-38.27,-0.009,0.55644,0.00058,...,0.00058,33.76342,-2.77904,-0.0,0.36823,161.0,2093.75,9 x 19,1935.70,2264.71

In [61]:
options_data_clean.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 37927 entries, 2023-10-03 to 2023-10-21
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   symbol               37927 non-null  object
 1   underlying_last      37927 non-null  float64
 2   expire_date          37927 non-null  object
 3   expiry_type          37927 non-null  object
 4   dte                  37927 non-null  float64
 5   strike               37927 non-null  float64
 6   strike_distance      37927 non-null  float64
 7   strike_distance_pct  37927 non-null  float64
 8   c_delta              37927 non-null  float64
 9   c_gamma              37927 non-null  float64
 10  c_vega               37927 non-null  float64
 11  c_theta              37927 non-null  float64
 12  c_rho                37927 non-null  float64
 13  c_iv                 37927 non-null  float64
 14  c_volume             37927 non-null  float64
 15  c_last               37927 non-null  float64
 16  c_size               37927 non-null  object
 17  c_bid                37927 non-null  float64
 18  c_ask                37927 non-null  float64
 19  p_delta              37927 non-null  float64
 20  p_gamma              37927 non-null  float64
 21  p_vega               37927 non-null  float64
 22  p_theta              37927 non-null  float64
 23  p_rho                37927 non-null  float64
 24  p_iv                 37927 non-null  float64
 25  p_volume             37927 non-null  float64
 26  p_last               37927 non-null  float64
 27  p_size               37927 non-null  object
 28  p_bid                37927 non-null  float64
 29  p_ask                37927 non-null  float64
dtypes: float64(25), object(5)
memory usage: 9.0+ MB

In [62]:
options_data_clean.describe()

,underlying_last,dte,strike,strike_distance,strike_distance_pct,c_delta,c_gamma,c_vega,c_theta,c_rho,...,p_delta,p_gamma,p_vega,p_theta,p_rho,p_iv,p_volume,p_last,p_bid,p_ask
count,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,...,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000
mean,4312.455213,7.685236,4300.000000,-12.455213,-0.002883,0.509278,0.000311,102.634642,-2.365949,4.866324,...,-0.490722,0.000311,102.634642,-2.475356,-3.813059,1.021768,55.982203,1841.230592,1694.617517,2000.778508
std,8.627450,7.627410,83.928542,84.370807,0.019566,0.042258,0.000349,61.461253,1.545121,8.611493,...,0.042258,0.000349,61.461253,1.544435,7.943548,1.155950,48.330037,302.030433,295.277722,307.695912
min,4291.010000,0.330000,4100.000000,-229.690000,-0.053000,0.385360,0.000010,25.183550,-7.818920,0.000000,...,-0.614640,0.000010,25.183550,-7.913230,-39.057880,0.205330,2.000000,1299.240000,1168.520000,1444.580000
25%,4306.440000,2.380000,4250.000000,-64.150000,-0.015000,0.474250,0.000060,66.549230,-3.246760,0.000000,...,-0.525750,0.000060,66.549230,-3.357795,-3.601300,0.286195,19.000000,1500.125000,1360.195000,1654.485000
50%,4312.340000,3.420000,4300.000000,-12.420000,-0.003000,0.508460,0.000160,79.875280,-2.026250,0.674150,...,-0.491540,0.000160,79.875280,-2.140060,0.000000,0.532010,34.000000,1991.960000,1839.030000,2157.460000
75%,4318.850000,17.490000,4350.000000,39.510000,0.009000,0.542570,0.000420,180.487000,-1.082425,5.909820,...,-0.457430,0.000420,180.487000,-1.192375,-0.000000,1.191290,91.000000,2089.935000,1934.690000,2259.620000
max,4329.690000,18.600000,4500.000000,208.990000,0.049000,0.632360,0.001450,186.222070,-0.326850,38.626890,...,-0.367640,0.001450,186.222070,-0.424660,-0.000000,6.041340,225.000000,2194.950000,2062.740000,2335.640000

In [63]:
# Define target date and strike price for filtering
date = ['2023-10-02','2023-10-03']
strike = 4300

# Filter df to select rows where index matches given dates ans strike price (k)
options_data_clean[(options_data_clean.index.normalize().isin(date)) &
                   (options_data_clean.strike == strike)][[
                                                         'symbol','strike','expire_date'
]]

C:\Users\Hassa\AppData\Local\Temp\ipykernel_30104\3290938144.py:6: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  options_data_clean[(options_data_clean.index.normalize().isin(date)) &

           symbol  strike expire_date

2023-10-03    SPX  4300.0  2023-10-03
2023-10-03    SPX  4300.0  2023-10-03
2023-10-03    SPX  4300.0  2023-10-03
2023-10-03    SPX  4300.0  2023-10-03
2023-10-03    SPX  4300.0  2023-10-03
...           ...     ...         ...
2023-10-03    SPX  4300.0  2023-10-03
2023-10-03    SPX  4300.0  2023-10-03
2023-10-03    SPX  4300.0  2023-10-03
2023-10-03    SPX  4300.0  2023-10-03
2023-10-03    SPX  4300.0  2023-10-03

[391 rows x 3 columns]

#### 1) Filter based on Liquidity measures to remove Illiquid Options

In [64]:
# Filter out options where the call ("c_size") or put ("p_size") has a size of '0 x 0'
# This removes contracts with no market depth (no available bids or asks)
options_data_clean = options_data_clean[(options_data_clean['c_size'] != '0 x 0')
                                    & (options_data_clean['p_size'] != '0 x 0')]

# Display the filtered options data
options_data_clean.head()

,symbol,underlying_last,expire_date,expiry_type,dte,strike,strike_distance,strike_distance_pct,c_delta,c_gamma,...,p_gamma,p_vega,p_theta,p_rho,p_iv,p_volume,p_last,p_size,p_bid,p_ask
,,,,,,,,,,,,,,,,,,,,,
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4250.0,-58.27,-0.014,0.58545,0.00036,...,0.00036,33.76342,-4.23265,-0.0,0.58064,205.0,2077.43,3 x 7,1915.47,2253.08
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4255.0,-53.27,-0.012,0.57824,0.00040,...,0.00040,33.76342,-3.81277,-0.0,0.51929,169.0,2081.41,3 x 6,1920.42,2255.89
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4260.0,-48.27,-0.011,0.57101,0.00045,...,0.00045,33.76342,-3.43054,-0.0,0.46344,216.0,2085.45,1 x 17,1925.43,2258.77
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4265.0,-43.27,-0.010,0.56374,0.00051,...,0.00051,33.76342,-3.08596,-0.0,0.41309,199.0,2089.57,10 x 7,1930.53,2261.71
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4270.0,-38.27,-0.009,0.55644,0.00058,...,0.00058,33.76342,-2.77904,-0.0,0.36823,161.0,2093.75,9 x 19,1935.70,2264.71

#### 2) Filter based on strike distance relative to underlying price to focus on relevant contracts

In [65]:
# Filter out options where the strike distance percentage is greater than 5%
# This helps remove strikes that are too far from the underlying price, focusing on relevant contracts
options_data_clean = options_data_clean[
    options_data_clean.strike_distance_pct <= 0.05]

# Display the filtered options data
options_data_clean.head()

,symbol,underlying_last,expire_date,expiry_type,dte,strike,strike_distance,strike_distance_pct,c_delta,c_gamma,...,p_gamma,p_vega,p_theta,p_rho,p_iv,p_volume,p_last,p_size,p_bid,p_ask
,,,,,,,,,,,,,,,,,,,,,
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4250.0,-58.27,-0.014,0.58545,0.00036,...,0.00036,33.76342,-4.23265,-0.0,0.58064,205.0,2077.43,3 x 7,1915.47,2253.08
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4255.0,-53.27,-0.012,0.57824,0.00040,...,0.00040,33.76342,-3.81277,-0.0,0.51929,169.0,2081.41,3 x 6,1920.42,2255.89
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4260.0,-48.27,-0.011,0.57101,0.00045,...,0.00045,33.76342,-3.43054,-0.0,0.46344,216.0,2085.45,1 x 17,1925.43,2258.77
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4265.0,-43.27,-0.010,0.56374,0.00051,...,0.00051,33.76342,-3.08596,-0.0,0.41309,199.0,2089.57,10 x 7,1930.53,2261.71
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4270.0,-38.27,-0.009,0.55644,0.00058,...,0.00058,33.76342,-2.77904,-0.0,0.36823,161.0,2093.75,9 x 19,1935.70,2264.71

#### 3) Filter out all contract values =< 0

In [66]:
options_data_clean = options_data_clean[(options_data_clean["c_last"] > 0.0)
                                    & (options_data_clean["p_last"] > 0.0)]
options_data_clean.head()

,symbol,underlying_last,expire_date,expiry_type,dte,strike,strike_distance,strike_distance_pct,c_delta,c_gamma,...,p_gamma,p_vega,p_theta,p_rho,p_iv,p_volume,p_last,p_size,p_bid,p_ask
,,,,,,,,,,,,,,,,,,,,,
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4250.0,-58.27,-0.014,0.58545,0.00036,...,0.00036,33.76342,-4.23265,-0.0,0.58064,205.0,2077.43,3 x 7,1915.47,2253.08
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4255.0,-53.27,-0.012,0.57824,0.00040,...,0.00040,33.76342,-3.81277,-0.0,0.51929,169.0,2081.41,3 x 6,1920.42,2255.89
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4260.0,-48.27,-0.011,0.57101,0.00045,...,0.00045,33.76342,-3.43054,-0.0,0.46344,216.0,2085.45,1 x 17,1925.43,2258.77
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4265.0,-43.27,-0.010,0.56374,0.00051,...,0.00051,33.76342,-3.08596,-0.0,0.41309,199.0,2089.57,10 x 7,1930.53,2261.71
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4270.0,-38.27,-0.009,0.55644,0.00058,...,0.00058,33.76342,-2.77904,-0.0,0.36823,161.0,2093.75,9 x 19,1935.70,2264.71

#### 4) Filter based IV values to weed out unreliable data

In [67]:
# Remove rows where either the call option's implied volatility ("c_iv") or the put option's implied volatility ("p_iv") is missing (NaN)
# This ensures we only work with options that have valid implied volatility values
options_data_clean = options_data_clean.dropna(subset=["c_iv", "p_iv"])

# Display the filtered options data
options_data_clean.head()

,symbol,underlying_last,expire_date,expiry_type,dte,strike,strike_distance,strike_distance_pct,c_delta,c_gamma,...,p_gamma,p_vega,p_theta,p_rho,p_iv,p_volume,p_last,p_size,p_bid,p_ask
,,,,,,,,,,,,,,,,,,,,,
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4250.0,-58.27,-0.014,0.58545,0.00036,...,0.00036,33.76342,-4.23265,-0.0,0.58064,205.0,2077.43,3 x 7,1915.47,2253.08
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4255.0,-53.27,-0.012,0.57824,0.00040,...,0.00040,33.76342,-3.81277,-0.0,0.51929,169.0,2081.41,3 x 6,1920.42,2255.89
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4260.0,-48.27,-0.011,0.57101,0.00045,...,0.00045,33.76342,-3.43054,-0.0,0.46344,216.0,2085.45,1 x 17,1925.43,2258.77
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4265.0,-43.27,-0.010,0.56374,0.00051,...,0.00051,33.76342,-3.08596,-0.0,0.41309,199.0,2089.57,10 x 7,1930.53,2261.71
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4270.0,-38.27,-0.009,0.55644,0.00058,...,0.00058,33.76342,-2.77904,-0.0,0.36823,161.0,2093.75,9 x 19,1935.70,2264.71

#### 5) Filter based on bid and ask values of calls and puts (remove ones with 0 bids or asks)

In [68]:
# Remove options where either the call or put bid/ask prices are zero
# This ensures that only actively traded options with valid market quotes are kept
options_data_clean = options_data_clean[(options_data_clean.c_bid != 0.0) 
                                    & (options_data_clean.p_bid != 0.0) 
                                    & (options_data_clean.c_ask != 0.0) 
                                    & (options_data_clean.p_ask != 0.0)]

# Display the filtered options data
options_data_clean.head()

,symbol,underlying_last,expire_date,expiry_type,dte,strike,strike_distance,strike_distance_pct,c_delta,c_gamma,...,p_gamma,p_vega,p_theta,p_rho,p_iv,p_volume,p_last,p_size,p_bid,p_ask
,,,,,,,,,,,,,,,,,,,,,
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4250.0,-58.27,-0.014,0.58545,0.00036,...,0.00036,33.76342,-4.23265,-0.0,0.58064,205.0,2077.43,3 x 7,1915.47,2253.08
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4255.0,-53.27,-0.012,0.57824,0.00040,...,0.00040,33.76342,-3.81277,-0.0,0.51929,169.0,2081.41,3 x 6,1920.42,2255.89
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4260.0,-48.27,-0.011,0.57101,0.00045,...,0.00045,33.76342,-3.43054,-0.0,0.46344,216.0,2085.45,1 x 17,1925.43,2258.77
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4265.0,-43.27,-0.010,0.56374,0.00051,...,0.00051,33.76342,-3.08596,-0.0,0.41309,199.0,2089.57,10 x 7,1930.53,2261.71
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4270.0,-38.27,-0.009,0.55644,0.00058,...,0.00058,33.76342,-2.77904,-0.0,0.36823,161.0,2093.75,9 x 19,1935.70,2264.71

In [69]:
# Display a concise summary of the options_data_clean
options_data_clean.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 37927 entries, 2023-10-03 to 2023-10-21
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   symbol               37927 non-null  object
 1   underlying_last      37927 non-null  float64
 2   expire_date          37927 non-null  object
 3   expiry_type          37927 non-null  object
 4   dte                  37927 non-null  float64
 5   strike               37927 non-null  float64
 6   strike_distance      37927 non-null  float64
 7   strike_distance_pct  37927 non-null  float64
 8   c_delta              37927 non-null  float64
 9   c_gamma              37927 non-null  float64
 10  c_vega               37927 non-null  float64
 11  c_theta              37927 non-null  float64
 12  c_rho                37927 non-null  float64
 13  c_iv                 37927 non-null  float64
 14  c_volume             37927 non-null  float64
 15  c_last               37927 non-null  float64
 16  c_size               37927 non-null  object
 17  c_bid                37927 non-null  float64
 18  c_ask                37927 non-null  float64
 19  p_delta              37927 non-null  float64
 20  p_gamma              37927 non-null  float64
 21  p_vega               37927 non-null  float64
 22  p_theta              37927 non-null  float64
 23  p_rho                37927 non-null  float64
 24  p_iv                 37927 non-null  float64
 25  p_volume             37927 non-null  float64
 26  p_last               37927 non-null  float64
 27  p_size               37927 non-null  object
 28  p_bid                37927 non-null  float64
 29  p_ask                37927 non-null  float64
dtypes: float64(25), object(5)
memory usage: 9.0+ MB

#### Adding columns

In [70]:
# Compute call and put midpoints
options_data_clean['c_mid'] = (options_data_clean['c_bid'] + options_data_clean['c_ask']) / 2
options_data_clean['p_mid'] = (options_data_clean['p_bid'] + options_data_clean['p_ask']) / 2

In [71]:
# Compute call and put spreads
options_data_clean['c_spread'] = options_data_clean['c_ask'] - options_data_clean['c_bid']
options_data_clean['p_spread'] = options_data_clean['p_ask'] - options_data_clean['p_bid']

In [72]:
options_data_clean.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 37927 entries, 2023-10-03 to 2023-10-21
Data columns (total 34 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   symbol               37927 non-null  object
 1   underlying_last      37927 non-null  float64
 2   expire_date          37927 non-null  object
 3   expiry_type          37927 non-null  object
 4   dte                  37927 non-null  float64
 5   strike               37927 non-null  float64
 6   strike_distance      37927 non-null  float64
 7   strike_distance_pct  37927 non-null  float64
 8   c_delta              37927 non-null  float64
 9   c_gamma              37927 non-null  float64
 10  c_vega               37927 non-null  float64
 11  c_theta              37927 non-null  float64
 12  c_rho                37927 non-null  float64
 13  c_iv                 37927 non-null  float64
 14  c_volume             37927 non-null  float64
 15  c_last               37927 non-null  float64
 16  c_size               37927 non-null  object
 17  c_bid                37927 non-null  float64
 18  c_ask                37927 non-null  float64
 19  p_delta              37927 non-null  float64
 20  p_gamma              37927 non-null  float64
 21  p_vega               37927 non-null  float64
 22  p_theta              37927 non-null  float64
 23  p_rho                37927 non-null  float64
 24  p_iv                 37927 non-null  float64
 25  p_volume             37927 non-null  float64
 26  p_last               37927 non-null  float64
 27  p_size               37927 non-null  object
 28  p_bid                37927 non-null  float64
 29  p_ask                37927 non-null  float64
 30  c_mid                37927 non-null  float64
 31  p_mid                37927 non-null  float64
 32  c_spread             37927 non-null  float64
 33  p_spread             37927 non-null  float64
dtypes: float64(29), object(5)
memory usage: 10.1+ MB

In [74]:
options_data_clean.describe()

,underlying_last,dte,strike,strike_distance,strike_distance_pct,c_delta,c_gamma,c_vega,c_theta,c_rho,...,p_rho,p_iv,p_volume,p_last,p_bid,p_ask,c_mid,p_mid,c_spread,p_spread
count,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,...,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000,37927.000000
mean,4312.455213,7.685236,4300.000000,-12.455213,-0.002883,0.509278,0.000311,102.634642,-2.365949,4.866324,...,-3.813059,1.021768,55.982203,1841.230592,1694.617517,2000.778508,2168.011169,1847.698012,360.012327,306.160991
std,8.627450,7.627410,83.928542,84.370807,0.019566,0.042258,0.000349,61.461253,1.545121,8.611493,...,7.943548,1.155950,48.330037,302.030433,295.277722,307.695912,16.155686,301.438994,54.819765,16.417835
min,4291.010000,0.330000,4100.000000,-229.690000,-0.053000,0.385360,0.000010,25.183550,-7.818920,0.000000,...,-39.057880,0.205330,2.000000,1299.240000,1168.520000,1444.580000,2126.185000,1306.550000,263.950000,272.900000
25%,4306.440000,2.380000,4250.000000,-64.150000,-0.015000,0.474250,0.000060,66.549230,-3.246760,0.000000,...,-3.601300,0.286195,19.000000,1500.125000,1360.195000,1654.485000,2159.205000,1507.320000,316.555000,292.910000
50%,4312.340000,3.420000,4300.000000,-12.420000,-0.003000,0.508460,0.000160,79.875280,-2.026250,0.674150,...,0.000000,0.532010,34.000000,1991.960000,1839.030000,2157.460000,2164.965000,1998.350000,339.120000,306.800000
75%,4318.850000,17.490000,4350.000000,39.510000,0.009000,0.542570,0.000420,180.487000,-1.082425,5.909820,...,-0.000000,1.191290,91.000000,2089.935000,1934.690000,2259.620000,2173.295000,2096.240000,424.640000,318.230000
max,4329.690000,18.600000,4500.000000,208.990000,0.049000,0.632360,0.001450,186.222070,-0.326850,38.626890,...,-0.000000,6.041340,225.000000,2194.950000,2062.740000,2335.640000,2231.335000,2199.190000,448.710000,355.040000

#### Separate Calls and Puts Data

In [75]:
# Selecting common columns
common_cols = [ 'symbol',
               'underlying_last', 'expire_date',  'expiry_type', 'dte', 'strike', 
               'strike_distance', 'strike_distance_pct']

# Selecting call option columns (columns starting with 'c_')
call_cols = common_cols + [col for col in options_data_clean.columns if col.startswith('c_')]

# Selecting put option columns (columns starting with 'p_')
put_cols = common_cols + [col for col in options_data_clean.columns if col.startswith('p_')]

# Creating call and put DataFrames
call_options_data = options_data_clean[call_cols].copy()
put_options_data = options_data_clean[put_cols].copy()

call_options_data.head()

,symbol,underlying_last,expire_date,expiry_type,dte,strike,strike_distance,strike_distance_pct,c_delta,c_gamma,...,c_theta,c_rho,c_iv,c_volume,c_last,c_size,c_bid,c_ask,c_mid,c_spread
,,,,,,,,,,,,,,,,,,,,,
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4250.0,-58.27,-0.014,0.58545,0.00036,...,-4.11692,2.18091,0.54668,207.0,2161.30,9 x 6,2024.71,2307.11,2165.910,282.40
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4255.0,-53.27,-0.012,0.57824,0.00040,...,-3.69690,1.99935,0.49091,198.0,2160.31,3 x 20,2022.42,2307.61,2165.015,285.19
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4260.0,-48.27,-0.011,0.57101,0.00045,...,-3.31453,1.81650,0.44013,201.0,2159.39,1 x 18,2020.18,2308.18,2164.180,288.00
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4265.0,-43.27,-0.010,0.56374,0.00051,...,-2.96982,1.63243,0.39436,196.0,2158.53,3 x 12,2018.01,2308.84,2163.425,290.83
2023-10-03,SPX,4308.27,2023-10-03,Daily,0.6,4270.0,-38.27,-0.009,0.55644,0.00058,...,-2.66276,1.44722,0.35359,218.0,2157.75,6 x 4,2015.90,2309.57,2162.735,293.67

#### Export Calls and Puts Data

In [76]:
call_options_data.to_csv(r"C:\Users\Hassa\OneDrive - Loughborough University\current\Algorthmic Trading for Beginners\Data Management\datamodules\minute_options_data\call_options_data.csv")
put_options_data.to_csv(r"C:\Users\Hassa\OneDrive - Loughborough University\current\Algorthmic Trading for Beginners\Data Management\datamodules\minute_options_data\put_options_data.csv")